apiVersion: telekom.breakglass.de/v1alpha1
kind: ClusterGroupAccess
metadata:
  labels:
  name: kind-sample
spec:
  cluster: kind
  users:
  - username: tester
    groups: [foo, bar, breakglass-service-create]
  requests:
  - for_user: 
      username: tester
      groups: [another, other]
    approvers: [bazko1@deutche.de, jakob@deutche.de, max@deutche.de]
