apiVersion: telekom.breakglass.de/v1alpha1
kind: ClusterAccessReviewList
items:
  - metadata:
      name: clusteraccessreview-sample-1
    spec:
      application_status: pending
      cluster: kind
      duration: "10s"
      until: '2025-07-21T17:32:28Z'
      subject:
        resource: services
        username: foobar
        verb: create
  - metadata:
      name: clusteraccessreview-sample-2
    spec:
      application_status: accepted
      cluster: kind
      duration: "24h"
      until: '2025-07-21T17:32:28Z'
      subject:
        namespace: kube-system
        resource: services
        username: tester
        verb: create
  - metadata:
      name: clusteraccessreview-sample-3
    spec:
      application_status: rejected
      cluster: kind
      duration: "20m"
      until: '2025-07-21T17:32:28Z'
      subject:
        namespace: default
        resource: pods
        username: unknown
        verb: create
  - metadata:
      name: clusteraccessreview-sample-4
    spec:
      application_status: accepted
      cluster: master
      duration: "20m"
      until: '2025-07-21T17:32:28Z'
      subject:
        namespace: default
        resource: pods
        username: unknown
        verb: create
  - metadata:
      name: clusteraccessreview-sample-5
    spec:
      application_status: pending
      cluster: kind
      duration: "20m"
      until: '2024-11-06T17:32:28Z'
      subject:
        namespace: default
        resource: services
        username: unknown
        verb: create
