apiVersion: telekom.breakglass.de/v1alpha1
kind: ClusterAccessReview
metadata:
  labels:
    app.kubernetes.io/name: scaffoldcrd
    app.kubernetes.io/managed-by: kustomize
  name: clusteraccessreview-sample
spec:
  application_status: pending
  cluster: kind
  duration: "10h"
  until: '2024-11-19T17:39:28+01:00'
  subject:
    resource: services
    username: foobar
    verb: create
