apiVersion: v1
kind: Service
metadata:
  labels:
    app: breakglass
  name: breakglass
  namespace: system
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
    nodePort: 30081
  selector:
    app: breakglass
  type: NodePort
