apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIIAbPmd+FZH68wDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNDA5MzAxMDA0MTJaFw0zNDA5MjgxMDA5MTJaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC1nToR1Lv/EEXDxM5+/W7VKkgyFcYxvf7FvMiUKq36qcU6kVZzofmgWeY8
    db34ogQKrSsDFK72PnHsosO7M/lIx+YI3AKpQfyTAya5Eo44aQd+2cqrbCDDKysH
    +wl3UnuJynpaQPTiux8B4nFUJXzjR0El9WWfOYLrQNK6y+U5fFWOtLhOLlA9vm37
    bcJWGzRRr+vWEw734hPkBcBVnQLarhsu1UkFIWHeWi3yJzbJ8oF1Fjzn4Z3shaxb
    0RjU9jcTYSsdiTwYnzEZW9k+uPUuXtmwtDoxOHrK2Hb2lgHRI6Ovdhtt9kszD72a
    HsLl3LCwRJwtqaML0cuSc7qjTtavAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTa+xi7I7cy8s+6DcM4BH8xLBNj5TAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQCCp0d4Or3G
    UKobwuAxnwLYbQEadJ3k8b9uin1YpZX0IBz7lR7obsdQoJUXiGBx+iOGHJXGd8Np
    Ntcp5O32zBI29aHerWbsvOk2B1H9Hd/Q1EYk9rh0R2PW7/2WhB5YidxaTxiBaPcw
    baA4NhBar0MWwDhnbMxAgHUB4YFGQi/hcjT4UJk1hKvqaQbz+qfRNN0AtnCEVj6N
    eV1yIs4wRvQeNUsd0g+djlNnoqVidUJSFaOi14F5GwYo5yjki6FVYN4XbjBTCRtH
    NgXCb0YX9QrlCfdI91p4WIG4wedVZ8Xo/V9x2hQ29vmNFHOo0G/ScEMr9coBvucn
    F3desgZyJsnS
    -----END CERTIFICATE-----
  ca.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAtZ06EdS7/xBFw8TOfv1u1SpIMhXGMb3+xbzIlCqt+qnFOpFW
    c6H5oFnmPHW9+KIECq0rAxSu9j5x7KLDuzP5SMfmCNwCqUH8kwMmuRKOOGkHftnK
    q2wgwysrB/sJd1J7icp6WkD04rsfAeJxVCV840dBJfVlnzmC60DSusvlOXxVjrS4
    Ti5QPb5t+23CVhs0Ua/r1hMO9+IT5AXAVZ0C2q4bLtVJBSFh3lot8ic2yfKBdRY8
    5+Gd7IWsW9EY1PY3E2ErHYk8GJ8xGVvZPrj1Ll7ZsLQ6MTh6yth29pYB0SOjr3Yb
    bfZLMw+9mh7C5dywsEScLamjC9HLknO6o07WrwIDAQABAoIBAQCL746r6I/Gc4Jd
    2soFXT9F7mNcfByPfUbOk6y1RcFyT9eRTiUfyeFu5XYahdqPtj6I/28R26EISYs8
    exl3qA9fPe+ISgWe5yI3IIl4tsxwuLS20BdySEliOGParVpY32wi+qmV21EVVnsI
    17Lc1FnLQb74AYKA0i6HGBaHKc4AoPjugK8HJZZ2xsvj3mdTPhz+l11AsjXVkHl5
    /5yURPEZtHWBRUzfrz98pZj9hkoeTZEZIviyJryowRAEYMEfB9pyOSDX/JVDhcGG
    V4Q8E8UZmfEzvqNVgnECuX8BMtaPbKuXLE5PlGsmBvxFAHcLxDaYhIftU8rPdxjM
    H4+jpOhZAoGBAMtuEUb3SMOfH1Pp5+9vy5nmVXYYZOObLZs1bbEWPbMz080gplUL
    fD9y2euBwOZfQOP0VakKILAr9Ace0TR2xlBkWUDEV+DLiTchxOHvixpQcNkfn/Ru
    GwAmQsDmClyrt++G4jcVEtft7eneZNrLrhInUd1tbR6E4zWidvEURN47AoGBAOSL
    7v9a8GkN8ZYG8jDXXlwQjgtCMpMgxT8dPNwFDxz2aY+SQgD+dzPzf3Xaumu1Ys0T
    4IMMufbLPeq+1Vm3GRh40ZWHOQFi0bQrFN3poTkegt9L5SKIX+8V/UeS9kKbW+Gk
    0bFwVOtsLXXYH1bQ9yvPo2DOhiNJHmQJQ0BDOF4dAoGAKnafRKD5n1vnvixlLaW4
    ajeaPzx4UsphirRsYTqzRmTbIUZfcgEjvlrLAk3jZjMb6HloKBDlIeEK3zGfmcPx
    QXaw6sQRU+soiUmTP1YxQxzncWsYiH0zRaS26m0aXJ27l1QghD7x4ADaWKcDhmhd
    vYxXmlDtJiG3C8sN6OTCO2ECgYB29HqmAHBHTdGjk+P1FfPwGVHFfGQUficMLayi
    nCN8oKja6HZgTBJBQQjjj8AeFZ/iO+lMbJBSawDEMSWc95chTKlRmbtLBGM/0nie
    9F5M+5uEm90cdzzvlVNqMIzqqDBPptjZ8SzSCFE1GBNfvY4ZCI7x8SySKxmdWdDe
    Ht605QKBgDM90r1AoyBMwyjqriPPQgfNN3z1l16iFATybxIvsrOBySwziq/iyDeF
    eai97Hx48t9q0t4glmNHAorsdRwPk52mlGiKIZUGJYXZ7DtadnJ5V5Aegsde4Q/b
    clXq2JrfDAenoyBM1QsdnlIrsLy7IYLkG/N5K51NfMt0PUvxUJ60
    -----END RSA PRIVATE KEY-----
kind: ConfigMap
metadata:
  name: certs
  namespace: system
