- op: add
  path: /spec/template/spec/initContainers
  value:
  - name: wait-for-keycloak
    image: radial/busyboxplus:curl
    args:
    - /bin/sh
    - -c
    - >
      set -x;
      while [ $(curl -sw '%{http_code}' "http://breakglass-dev-keycloak:8080/realms/master/protocol/openid-connect/certs" -o /dev/null) -ne 200 ]; do
        sleep 5;
      done
