apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: system
  labels:
    app: mailhog
  name: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mailhog
    spec:
      containers:
      - image: mailhog/mailhog:latest 
        name: mailhog
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailhog
  name: mailhog
  namespace: system
spec:
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8025
    protocol: TCP
    targetPort: 8025
    name: 8025-8025
    nodePort: 30084
  - port: 1025
    protocol: TCP
    targetPort: 1025
    name: 1025-1025
  selector:
    app: mailhog
  sessionAffinity: None
  type: ClusterIP
